Bun.build({
  entrypoints: ["./zero/zero-schema.ts"],
  naming: { entry: "index.js" },
  outdir: "../zero-schema/src",
  external: [
    "drizzle-orm",
    "drizzle-kit",
    "drizzle-zero",
    "tsx",
    "dotenv",
    "dotenv-cli",
    "@rocicorp/zero",
    "../src",
  ],
  format: "esm",
  target: "browser",
  conditions: ["browser", "development"],
  packages: "external",
  banner:
    "// THIS FILE IS AUTO GENERATED BY `packages/db/zero/build-zero-schema.ts`. DO NOT EDIT MANUALLY. SEE `packages/db/zero/zero-schema` TO SEE HOW TO UPDATE",
});
